# -*- coding: utf-8 -*-
"""Ruby Briggs - GenAI Text to Image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqVQlqqF-FajW8PnUFq5PX3wZNFCEJmG
"""

!pip install transformers diffusers torch pillow gradio

from diffusers import StableDiffusionPipeline
import torch
import gradio as gr
from PIL import Image

import warnings
warnings.filterwarnings("ignore")

# Load the model
model_id = "runwayml/stable-diffusion-v1-5"
token = ""
pipe = StableDiffusionPipeline.from_pretrained(model_id, use_auth_token=token, torch_dtype=torch.float16)
pipe.to("cuda")  # Move model to GPU

def generate_image(prompt):
    image = pipe(prompt).images[0]  # Generate image
    return image  # Return generated image

interface = gr.Interface(
    fn=generate_image,
    inputs=gr.Textbox(label="Enter Image Description"),
    outputs=gr.Image(label="Generated Image"),
    title="Gen AI Text-to-Image App",
    description="Enter a descriptive text to generate an image."
)

interface.launch(share = True, debug=True)

